### ISSUE TITLE
Alteração de regra de negócios - Prospecções (Prioridade +++)

### ISSUE THREAD

**Issue by RafaelMagnoC** [SESIDEV/BaseDeProjetos#14]
Contexto: A gestão deseja mensurar o impacto do esforço de prospecção da equipe. Para isso, estabeleceu uma métrica nova chamada "volume de negócios". O volume de negócios será o somatório de todos os valores estimados de negociação de projetos antes da emissão da proposta mais o somatório de todos os valores de proposta para uma determinada casa.
Este valor deverá ser incluído no contato inicial com a empresa ou durante as discussões de escopo.

Tarefas:
-Definir com Antonio: O valor é a soma da estimativa mais propostas ou uma vez com proposta, exclui-se o valor da estimativa da conta
- Incluir campo no modelo de prospecção
- Alterar views de inclusão e edição para receber a nova variável
- Ajustar backend para receber nova variável

**Comment by LeonNasc** [comment]
Ver commit #da021f5e
