### ISSUE TITLE
Atualização do dashboard da home (Prioridade +++)

### ISSUE THREAD

**Issue by RafaelMagnoC** [SESIDEV/BaseDeProjetos#15]
Contexto: Na página inicial do sistema é exibido um dashboard sumarizando o escopo das atividades dos institutos. Atualmente, ele exibe o seguinte:

- Receita (O valor de receitas de projetos de pesquisa inseridos pelo PMO operacional [Daniella e Ivone]) 
- Investimento (O valor de investimento dispendido pelos institutos inseridos pelo PMO operacional)
- Despesas (O valor de despesas de projetos de pesquisa e operacional inseridos pelo PMO operacional)
- Projetos (A soma de projetos ativos em execução para cada instituto.)
- Empresas (A soma de empresas com relacionamento para cada instituto.)
- Funil de vendas (O número de prospecções ativas no funil de vendas)
- Equipe (O número total de colaboradores ativos para cada instituto; puxar do módulo de colaboradores)
- Satisfação do cliente. (Métrica da Fraunhofer sobre satisfação dos clientes em projetos)

A gestão deseja incluir novos campos para visualização do dashboard inicial. Estes campos são o volume de negócios e o valor total de propostas (Ver issue #14 ). Além disso, em vista do QSMS não fazer mais parte da nossa gerencia, o índice de qualidade é desnecessário e deverá ser removido. Alterar o campo receita para receita por competência, receita por caixa, manter investimento e despesas. Os valores apresentados deverão ser verificados, pois Antônio exige confiabilidade destes dados.

Tarefas:
- Incluir valores de receita, receita por competência, receita por caixa, investimento e despesas na home por casa (implementar filtro de casa).
- Incluir novo campo volume de negócios na home por casa.
- Incluir valor total de propostas que será o somatório que todos os pesquisadores vão incluir desde o inicio do primieiro contato.
- Alterar imagem de background da área de Sustentabilidade
- Remover o área Índice de segurança e qualidade da home

**Comment by LeonNasc** [comment]
Alterações mescladas e em produção
