### ISSUE TITLE
Alterar descrição da aba "Gráficos"

### ISSUE THREAD

**Issue by RafaelMagnoC** [SESIDEV/BaseDeProjetos#17]
Contexto: A gestão solicitou a troca de nomenclatura da aba gráficos em funil de vendas para dashboard, pois considerou uma melhor opção.

Tarefas:
- Na página funil de vendas >> home, será alterado a nomenclatura da aba "gráficos" para "dashboard".

**Comment by LeonNasc** [comment]
Já alterado no sistema.
